use super::{core, runtime::RuntimeError, scheduler::Executable, stdio::StdIO};
pub mod alloc;
pub mod branch;
pub mod data;
pub mod locate;
mod math_operation;
pub mod mem;
pub mod operation;

#[derive(Debug, Clone)]
pub enum Asm {
    Core(core::CoreAsm),
    Return(branch::Return),
    CloseFrame(branch::CloseFrame),
    Alloc(alloc::Alloc),
    Realloc(alloc::Realloc),
    Free(alloc::Free),
    Mem(mem::Mem),
    Operation(operation::Operation),
    Data(data::Data),
    Access(alloc::Access),
    // AccessIdx(alloc::CheckIndex),
    Locate(locate::Locate),
    OffsetIdx(locate::LocateIndex),
    OffsetSP(locate::LocateOffsetFromStackPointer),
    Offset(locate::LocateOffset),
    If(branch::BranchIf),
    Try(branch::BranchTry),
    Label(branch::Label),
    Call(branch::Call),
    Goto(branch::Goto),
    // Switch(branch::BranchTable),
    Pop(usize),
}

impl<E: crate::vm::external::Engine> Executable<E> for Asm {
    fn execute<P: crate::vm::scheduler::SchedulingPolicy>(
        &self,
        program: &crate::vm::program::Program<E>,
        scheduler: &mut crate::vm::scheduler::Scheduler<P>,
        signal_handler: &mut crate::vm::signal::SignalHandler<E>,
        stack: &mut crate::vm::allocator::stack::Stack,
        heap: &mut crate::vm::allocator::heap::Heap,
        stdio: &mut crate::vm::stdio::StdIO,
        engine: &mut E,
        context: &crate::vm::scheduler::ExecutionContext<E::FunctionContext, E::PID, E::TID>,
    ) -> Result<(), RuntimeError> {
        match self {
            Asm::Operation(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Return(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::CloseFrame(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Data(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Access(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            // Asm::AccessIdx(value) => value.execute(program, scheduler, signal_handler, stack, heap, stdio, engine, context),
            Asm::If(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Label(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Call(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Goto(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Alloc(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Mem(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            // Asm::Switch(value) => value.execute(program, scheduler, signal_handler, stack, heap, stdio, engine, context),
            Asm::OffsetIdx(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Offset(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::OffsetSP(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Locate(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Core(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Pop(size) => {
                stack.pop(*size)?;
                scheduler.next();
                Ok(())
            }
            Asm::Realloc(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Free(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
            Asm::Try(value) => value.execute(
                program,
                scheduler,
                signal_handler,
                stack,
                heap,
                stdio,
                engine,
                context,
            ),
        }
    }
}

impl<E: crate::vm::external::Engine> crate::vm::AsmName<E> for Asm {
    fn name(&self, stdio: &mut StdIO, program: &crate::vm::program::Program<E>, engine: &mut E, pid : E::PID) {
        match self {
            Asm::Core(value) => value.name(stdio, program, engine, pid),
            Asm::Return(value) => value.name(stdio, program, engine, pid),
            Asm::CloseFrame(value) => value.name(stdio, program, engine, pid),
            Asm::Alloc(value) => value.name(stdio, program, engine, pid),
            Asm::Realloc(value) => value.name(stdio, program, engine, pid),
            Asm::Free(value) => value.name(stdio, program, engine, pid),
            Asm::Mem(value) => value.name(stdio, program, engine, pid),
            Asm::Operation(value) => value.name(stdio, program, engine, pid),
            Asm::Data(value) => value.name(stdio, program, engine, pid),
            Asm::Access(value) => value.name(stdio, program, engine, pid),
            // Asm::AccessIdx(value) => value.name(stdio, program, engine, pid),
            Asm::Offset(value) => value.name(stdio, program, engine, pid),
            Asm::OffsetIdx(value) => value.name(stdio, program, engine, pid),
            Asm::OffsetSP(value) => value.name(stdio, program, engine, pid),
            Asm::Locate(value) => value.name(stdio, program, engine, pid),
            Asm::If(value) => value.name(stdio, program, engine, pid),
            Asm::Label(value) => value.name(stdio, program, engine, pid),
            Asm::Call(value) => value.name(stdio, program, engine, pid),
            Asm::Goto(value) => value.name(stdio, program, engine, pid),
            // Asm::Switch(value) => value.name(stdio, program, engine, pid),
            Asm::Try(value) => value.name(stdio, program, engine, pid),
            Asm::Pop(n) => stdio.push_asm(engine, pid, &format!("pop {n}")),
        }
    }
}
impl crate::vm::AsmWeight for Asm {
    fn weight(&self) -> super::Weight {
        match self {
            Asm::Core(value) => value.weight(),
            Asm::Return(value) => value.weight(),
            Asm::CloseFrame(value) => value.weight(),
            Asm::Alloc(value) => value.weight(),
            Asm::Realloc(value) => value.weight(),
            Asm::Free(value) => value.weight(),
            Asm::Mem(value) => value.weight(),
            Asm::Operation(value) => value.weight(),
            Asm::Data(value) => value.weight(),
            Asm::Access(value) => value.weight(),
            Asm::OffsetSP(value) => value.weight(),
            Asm::Offset(value) => value.weight(),
            Asm::OffsetIdx(value) => value.weight(),
            Asm::Locate(value) => value.weight(),
            Asm::If(value) => value.weight(),
            Asm::Try(value) => value.weight(),
            Asm::Label(value) => value.weight(),
            Asm::Call(value) => value.weight(),
            Asm::Goto(value) => value.weight(),
            Asm::Pop(value) => super::Weight::ZERO,
        }
    }
}
